{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify-ingress
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.gotifyHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gotify
                port:
                  number: {{ .Values.gotify.servicePort }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: igotify-ingress
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.igotifyHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: igotify
                port:
                  number: {{ .Values.igotify.servicePort }}
{{- end }}

