# Default values for gotify
gotify:
  ingress:
    enabled: false
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: gotify.example.com
        paths:
          - path: /
            pathType: Prefix
  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""
  service:
    port: 1337
  env:
    TZ: "Europe/Berlin"
    GOTIFY_DEFAULTUSER_PASS: "change_this_admin_password"


# Default values for igotify.
replicaCount: 1

image:
  #repository: ghcr.io/androidseb25/igotify-notification-assist
  repository: cellexec/igotify
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "igotify-notification"
fullnameOverride: "igotify-notification"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /version
    port: 5000

readinessProbe:
  httpGet:
    path: /version
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: igotify-data
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: igotify-data
#   mountPath: "/app/data"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
